// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO3tguEvZx8ggM0e9IFvxjMAIiAXV99ig',
    appId: '1:66734429125:web:db52b4a278920496be71ac',
    messagingSenderId: '66734429125',
    projectId: 'mobilejobs-18747',
    authDomain: 'mobilejobs-18747.firebaseapp.com',
    storageBucket: 'mobilejobs-18747.firebasestorage.app',
    measurementId: 'G-8YHFMB1Z73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFHbUM0U_-r_98rUu7lu0-pdFkj1ZRdXU',
    appId: '1:66734429125:android:c5226a3b2c3881bfbe71ac',
    messagingSenderId: '66734429125',
    projectId: 'mobilejobs-18747',
    storageBucket: 'mobilejobs-18747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8hH6O_htP7SG2XI23ETkGbKePIzXza_A',
    appId: '1:66734429125:ios:d6783d6044d9d58abe71ac',
    messagingSenderId: '66734429125',
    projectId: 'mobilejobs-18747',
    storageBucket: 'mobilejobs-18747.firebasestorage.app',
    iosBundleId: 'com.example.mobileJobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8hH6O_htP7SG2XI23ETkGbKePIzXza_A',
    appId: '1:66734429125:ios:d6783d6044d9d58abe71ac',
    messagingSenderId: '66734429125',
    projectId: 'mobilejobs-18747',
    storageBucket: 'mobilejobs-18747.firebasestorage.app',
    iosBundleId: 'com.example.mobileJobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO3tguEvZx8ggM0e9IFvxjMAIiAXV99ig',
    appId: '1:66734429125:web:0b6d6fd0e2c2f1d2be71ac',
    messagingSenderId: '66734429125',
    projectId: 'mobilejobs-18747',
    authDomain: 'mobilejobs-18747.firebaseapp.com',
    storageBucket: 'mobilejobs-18747.firebasestorage.app',
    measurementId: 'G-4G66CJ547W',
  );
}
